name: Go CI

on:
  push:
    branches: [ "develop" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Build-DB  
      run: docker-compose build
          
    - name: Create-DB
      run: docker-compose up -d
      
    - name: Test
      run: go test -v main_test.go

  createPullRequest:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

#      - name: Make changes to pull request
#        run: date +%s > report.txt

      - name: Create Pull Request
#        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.TOKEN }}
#          commit-message: Update report
#          committer: GitHub <noreply@github.com>
#          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
#          signoff: false
          branch: develop
          base: main
          delete-branch: false
#          title: '[Auto Pull Request] Atualize a Issue com Aprove'
#          body: |
#            Comente como Aprovado ou Cancele o PR.
#            - Updated with *today's* date
#            - Auto-generated by [create-pull-request][1]
#
#            [1]: https://github.com/peter-evans/create-pull-request
