name: Go CI

on:
  push:
    branches: [ "develop" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Build-DB  
      run: docker-compose build
          
    - name: Create-DB
      run: docker-compose up -d
      
    - name: Test
      run: go test -v main_test.go

  Create-Pull-Request-Action:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: quangvo09/pull-request-action@v1
        name: Create PR to Main
        with:
          github_token: ${{ secrets.TOKEN }}
          branch_prefix: develop
          base_branch: main
          labels: develop,main
          assignees: diillson@hotmail.com
          reviewers: diillson@hotmail.com
#      - uses: quangvo09/pull-request-action@v1
#        name: Create PR to integration
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch_prefix: hotfix
#          base_branch: integration
#          labels: hotfix,integration
#          assignees: quangvo09
#          reviewers: quangvo09
