name: Go CI

on:
  push:
    branches: [ "develop" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Build-DB  
      run: docker-compose build
          
    - name: Create-DB
      run: docker-compose up -d
      
    - name: Test
      run: go test -v main_test.go

    - name: Auto Pull Request
    - uses: actions/checkout@v3

      # Make changes to pull request here

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
