name: Go CI-Test

on:
  push:
    branches: [ "develop" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Build-DB  
      run: docker-compose build
          
    - name: Create-DB
      run: docker-compose up -d
      
    - name: Test
      run: go test -v main_test.go

  pull-request:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "main"                      # If blank, default: master
          pr_title: "Pull-Request ${{ github.ref }} Na main" # Title of pull request
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
            - Revise o PR e Edite com uma mensagem de Aprove.

            _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
#          pr_reviewer: "diillson"                         # Comma-separated list (no spaces)
          pr_assignee: "diillson"                         # Comma-separated list (no spaces)
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_milestone: "JornadaGo"                       # Milestone name
          pr_draft: false                                    # Creates pull request as draft
          pr_allow_empty: false                              # Creates pull request even if there are no changes
          github_token: ${{ secrets.TOKEN }}      # If blank, default: secrets.GITHUB_TOKEN
