name: Gerando Pre-Release

on:
  pull_request:
    types: closed
    branches: [ "main" ]

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"

      - uses: "diillson/auto-release@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            .github/LICENSE.txt
            *.zip
            *.tar.gz